### ISSUE TITLE
Confict with CardIo plugin and Paypal payment plugin

### ISSUE THREAD

**Issue by zefrench** [card-io/card.io-Cordova-Plugin#23]
I'm using scan card (cardIO) plugin on my app and I have some call to the scan within my index.js in order to scan card that will not be used with a paypal account and it works like a charm.

BUT
I need to install the paypal plugin but as paypal plugin comes now with carIo library I get duplicate error : duplicate symbol _CardIOCurrentScanningOrientatio when I run the cordova build ios and.. the build failed.

I tried to remove the cardIO plugin but I get error on my app : Can't find variable: CardIO

Is it a way to use the both plugin ?

If you have any idea, tell me..

**Comment by terrorhawks** [comment]
I'm having the same problem. I get a compile error when I have both plugins.

`com.android.dex.DexException: Multiple dex files define Lio/card/payment/Validator;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)`

**Comment by jaypatel512** [comment]
Hey @terrorhawks @zefrench ! 

Late on this, but we are working on making some major changes to both cordova plugins. We are trying to make it such that you can use `CardIO.scan` methods available directly in paypal cordova plugin dependency.

Keep an eye on this pull request, and once it is in, you should be able to just depend on paypal cordova sdk, and get all the benefits of card.io cordova plugin too :) 

https://github.com/paypal/PayPal-Cordova-Plugin/pull/179

**Comment by jaypatel512** [comment]
Closing this issue, as the new version of PayPal-Cordova-Plugin will now allow you to use CardIO.scan feature directly. No need to install card.io-Cordova-Plugin separately.
